name: ROS CI

on: [push]

jobs:    
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.0.12
        with:
          required-ros-distributions: melodic
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install wheel
          pip install bluerobotics-ping
      - name: Build package
        run: |
          source /opt/ros/melodic/setup.bash
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          catkin build
          source devel/setup.bash
          cd ~/catkin_ws/src
          ln -s $CI_SOURCE_PATH
          catkin build
        env:
          CI_SOURCE_PATH: $GITHUB_WORKSPACE/ping360_sonar
      - name: Lint
        run: |
          cd ~/catkin_ws
          catkin build ping360_sonar --catkin-make-args roslint
